CREATE TABLE GeophysicalMeasurements (
    "index" DATETIME PRIMARY KEY,
    LAT FLOAT,
    LON FLOAT,
    CORR_DEPTH FLOAT,
    MAG_TOT FLOAT,
    MAG_RES FLOAT,
    GRA_OBS FLOAT,
    FREEAIR FLOAT
);
