[project]
name = "geonav"
version = "0.2.0"
description = "A simulator and database manager for geophysical navigation systems"
readme = "README.md"
authors = [{name="James Brodovsky"}]
requires-python = ">=3.8"
dependencies = [
    "anglewrapper",
    "python-ins",
    "numpy",
    "pandas",
    "filterpy",
    "pytz",
    "haversine",
    "pygmt",
    "numba",
    "matplotlib",
    "h5py",
    "sqlalchemy",
    "tqdm",
    "ruff",
    "scikit-learn"
]

[project.urls]
homepage = "https://github.com/jbrodovsky/geophysical_nav"

[project.scripts]
dbmgr = "data_management.dbmgr:main"

[build-system]
requires = ["scikit-build-core>=0.10", "pybind11"]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
minimum-version = "build-system.requires"
build-dir = "build/{wheel_tag}"

# PyTest
[tool.pytest]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py", "tests.py", "test.py"]
python_classes = ["Test*", "*Test"]
python_functions = ["test_*"]

[tool.pytest.ini_options]
pythonpath = "./src"
addopts = ["--import-mode=importlib", "--cov=src", "--cov-report=term-missing"]

[tool.ruff]
line-length = 120

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-64"]

[tool.pixi.dependencies]
# pytables = "*"
uv = "*"

[tool.pixi.tasks]
# clean = "find ./src -name '*.so' | grep . && find ./src -name '*.so' | xargs rm || true"
# build = {cmd = "rm -r dist; rm -r sdist; rm -r build; find ./src -name '*.so' | xargs rm; python -m build;"}
# install = {cmd = "pip install -e ."}

[tool.pixi.feature.dev.dependencies]
notebook = "*"

[tool.pixi.feature.test.dependencies]
pytest = "*"
pytest-cov = "*"
ruff = "*"

[tool.pixi.feature.test.tasks]
lint = "ruff format ."
test = {cmd = "coverage run -m pytest", depends-on = "lint"}

[tool.pixi.environments]
test = { features = ["test"], solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }
