name: geonav
channels:
  - defaults
  - conda-forge
  - Microsoft
dependencies:
  - python
  # Standard base scientific packages
  - numpy
  - pandas
  - pandas-stubs
  # building and speed
  - build
  - setuptools
  - wheel
  - mypy
  - numba
  # linting
  # - black
  # - flake8
  # - pylint
  - ruff
  # Testing
  - pytest
  - pytest-cov
  # Documentation
  - sphinx
  # Plotting tools
  - matplotlib
  - seaborn
  # Particle filter
  - filterpy
  - pytz
  - haversine
  - pygmt
  # Interactive tools
  - ipython
  - notebook
  - jupyter
  # Data handling
  - sqlite
  - sqlalchemy
  - sqlalchemy2-stubs
  - hdf5
  - h5py
  - netcdf4
  - pytables
  # Misc
  - tqdm
  
