name: geonav
channels:
  - defaults
  - conda-forge
  - Microsoft
dependencies:
  - python=3.11
  # building and speed
  - build
  - setuptools
  - wheel
  - mypy
  - numba
  # linting
  - black
  - flake8
  - pylint
  # Testing
  - pytest
  - pytest-cov
  # Documentation requirements
  - sphinx
  - pandoc
  # Particle filter
  - filterpy
  - numpy
  - pandas
  - pytz
  - haversine
  - pygmt
  # Plotting
  - matplotlib
  # Data handling
  - sqlite
  - sqlalchemy
  # Misc
  - notebook
  - tqdm
  
