[project]
dependencies = []
description = "Add a short description here"
name = "geophysical_nav"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
requires = ["setuptools", "wheel", "mypy", "build"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["geophysical", "data_management"]

[tool.pytest]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py", "tests.py", "test.py"]
python_classes = ["Test*", "*Test"]
python_functions = ["test_*"]

[tool.pytest.ini_options]
pythonpath = "./src"
addopts = ["--import-mode=importlib", "--cov=src", "--cov-report=term-missing"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
geophysical_nav = { path = ".", editable = true }
python-ins = "*"
anglewrapper = "*"

[tool.pixi.tasks]

[tool.pixi.dependencies]
numpy = "*"
pandas = "*"
filterpy = "*"
pytz = "*"
haversine = "*"
pygmt = "*"
numba = ">=0.60.0,<0.61"
matplotlib = ">=3.9.2,<4"
h5py = ">=3.12.1,<4"
sqlalchemy = ">=2.0.36,<3"
sqlite = ">=3.47.0,<4"
tqdm = ">=4.66.6,<5"
pytables = ">=3.10.1,<4"

[tool.pixi.feature.dev.dependencies]
notebook = "*"

[tool.pixi.feature.test.dependencies]
pytest = "*"
pytest-cov = "*"
ruff = "*"

[tool.pixi.feature.test.tasks]
test = "coverage run -m pytest"

[tool.pixi.environments]
test = { features = ["test"], solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }
