[project]
dependencies = []
description = "Add a short description here"
name = "geophysical-nav"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
requires = ["setuptools", "wheel", "build", "pybind11"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["geophysical", "data_management", "navtoolbox"]

[tool.pytest]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py", "tests.py", "test.py"]
python_classes = ["Test*", "*Test"]
python_functions = ["test_*"]

[tool.pytest.ini_options]
pythonpath = "./src"
addopts = ["--import-mode=importlib", "--cov=src", "--cov-report=term-missing"]

[tool.ruff]
line-length = 120

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
geophysical_nav = { path = ".", editable = true }
python-ins = "*"
anglewrapper = "*"
build = "*"
setuptools = "*"
wheel = "*"

[tool.pixi.tasks]
build = {cmd = "rm -r dist; rm -r sdist; rm -r build; python -m build;"}
install = {cmd = "WHL_FILE=$(find ./dist -name '*.whl'); python -m pip install $WHL_FILE --force-reinstall", depends-on="build"}

[tool.pixi.dependencies]
numpy = "*"
pandas = "*"
filterpy = "*"
pytz = "*"
haversine = "*"
pygmt = "*"
numba = "*"
matplotlib = "*"
h5py = "*"
sqlalchemy = "*"
sqlite = "*"
tqdm = "*"
pytables = "*"
pybind11 = ">=2.13.6,<3"
pip = ">=24.3.1,<25"
cxx-compiler = ">=1.8.0,<2"
libstdcxx-ng = ">=14.2.0,<15"

[tool.pixi.feature.dev.dependencies]
notebook = "*"

[tool.pixi.feature.test.dependencies]
pytest = "*"
pytest-cov = "*"
ruff = "*"

[tool.pixi.feature.test.tasks]
lint = "ruff format ."
test = {cmd = "coverage run -m pytest", depends-on = "lint"}

[tool.pixi.environments]
test = { features = ["test"], solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }
