[build-system]
requires = ["setuptools", "wheel", "mypy", "build"]
build-backend = "setuptools.build_meta"

[project]
name = "Geophyiscal_Navigation_Simulator"
version = "0.1.0"
requires-python = ">=3.12"
description = "A simulator and database manager for geophysical navigation systems"
readme = "README.md"
authors = [{name="James Brodovsky"}]


[project.urls]
homepage = "https://github.com/jbrodovsky/geophysical_nav"

[tool.black]
line-length = 120
target-version = ['py312']

[tool.isort]
profile = "black"

[tool.flake8]
max-line-length = 120
extend-ignore = "E203, W503"

[tool.pylint]
max-line-length = 120

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
show_error_codes = true
disallow_untyped_calls = true
disallow_untyped_defs = true
files=["src/ctest/fib.py"]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["ctest", "geophysical"]

[tool.pytest]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py", "tests.py", "test.py"]
python_classes = ["Test*", "*Test"]
python_functions = ["test_*"]

[tool.pytest.ini_options]
pythonpath = "src"
addopts = ["--import-mode=importlib", "--cov=src", "--cov-report=term-missing"]