"""
Utility functions for navigation toolbox
"""
from __future__ import annotations
import numpy
__all__ = ['compute_rms', 'mm_prod', 'mm_prod_symmetric', 'mv_prod', 'skew_matrix', 'to_180_range']
def compute_rms(data: numpy.ndarray[numpy.float64[m, 1]]) -> float:
    ...
def mm_prod(a: numpy.ndarray[numpy.float64[m, n]], b: numpy.ndarray[numpy.float64[m, n]], at: bool = False, bt: bool = False) -> numpy.ndarray[numpy.float64[m, n]]:
    ...
def mm_prod_symmetric(a: numpy.ndarray[numpy.float64[m, n]], b: numpy.ndarray[numpy.float64[m, n]]) -> numpy.ndarray[numpy.float64[m, n]]:
    ...
def mv_prod(a: numpy.ndarray[numpy.float64[m, n]], b: numpy.ndarray[numpy.float64[m, 1]], at: bool = False) -> numpy.ndarray[numpy.float64[m, 1]]:
    ...
def skew_matrix(vec: numpy.ndarray[numpy.float64[3, 1]]) -> numpy.ndarray[numpy.float64[3, 3]]:
    ...
def to_180_range(angle: float) -> float:
    ...
