# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - GeophysicalNavigation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://geonavcontainers.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1fd96737388b4b64b016e05c741cee41 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_63db9efb5ee94d88b4189b7b5936bd1e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: geonavcontainers.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1fd96737388b4b64b016e05c741cee41 }}/geonav:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'GeophysicalNavigation'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_cbc2c29b085c4e2ca7671b7941bd0ec5 }}
        images: 'geonavcontainers.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1fd96737388b4b64b016e05c741cee41 }}/geonav:${{ github.sha }}'