# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - GeophysicalNavigation

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: GeophysicalNavigation # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.11' # set this to the python version to use (supports 3.6, 3.7, 3.8)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python with Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          activate-environment: nav
          environment-file: requirements.yml
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda activate nav
          conda install pip conda-pack
          pip install -r requirements.txt
      - name: Pack environment for deployment
        shell: bash -l {0}
        run: |
          conda pack -n nav -o ./nav_env.tar.gz --ignore-missing-files
      # - name: Setup Python version
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: ${{ env.PYTHON_VERSION }}
      # 
      # - name: Create and start virtual environment
      #   run: |
      #     python -m venv venv
      #     source venv/bin/activate
      # 
      # - name: Install dependencies
      #   run: pip install -r requirements.txt
      # 
      # # Optional: Add step to run tests here
      # 
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip
          # path: |
          #   release.zip
          #   !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # environment:
    #   name: 'Production'
    #   url: ${{ steps.deploy-to-function.outputs.webapp-url }}
      
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
          mkdir nav
          tar -xzf nav_env.tar.gz -C nav
          source nav/bin/activate
          conda-unpack

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE}}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
