name: Run general CD testing and linting for python

on:
    push:
        branches: 
            - all

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.11

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install pytest flake8 black

            - name: Format and lint
              run: |
                pip install black flake8 pylint
                # Autoformat with black
                black .
                # stop the build if there are Python syntax errors or undefined names
                flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
                flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
                # lint with pylint
                pylint src test --fail-under=9.0 || exit 1
    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Run PyTest
              run: |
                pytest